using System;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace Mithril.Analyzers.Common;

internal static class GeneratedCodeDetector
{
    private static readonly string[] GeneratedSuffixes =
    [
        ".g.cs",
        ".generated.cs",
        ".designer.cs",
    ];

    public static bool IsGenerated(SyntaxTree tree, CancellationToken cancellationToken)
    {
        var filePath = tree.FilePath ?? string.Empty;
        foreach (var suffix in GeneratedSuffixes)
        {
            if (filePath.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        var text = tree.GetText(cancellationToken);
        var maxLinesToInspect = Math.Min(10, text.Lines.Count);
        for (var index = 0; index < maxLinesToInspect; index++)
        {
            var lineText = text.Lines[index].ToString();
            if (lineText.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
