using System.Threading.Tasks;
using Xunit;

namespace Mithril.Analyzers.Tests;

public sealed class FileTooLongAnalyzerTests
{
    [Fact]
    public async Task Reports_When_File_Exceeds_Configured_Limit()
    {
        var source = """
            namespace Sample;

            [|class|] Example
            {
                private int _value;

                public int Value => _value;
            }
            """;

        await AnalyzerVerifier<FileTooLongAnalyzer>.VerifyAnalyzerAsync(
            source,
            "BGA001");
    }

    [Fact]
    public async Task Ignores_AutoGenerated_Files()
    {
        var source = """
            // <auto-generated />
            namespace Sample;

            class Example
            {
                private int _value;

                public int Value => _value;
            }
            """;

        await AnalyzerVerifier<FileTooLongAnalyzer>.VerifyAnalyzerAsync(source);
    }
}
